version: '3.8'
services:
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: php-server
    restart: always
    ports:
      - 80:80 
    volumes:
      - ./html:/var/www/html
      # - ./config:/usr/local/etc/php
      # - ./config/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      # - ./config/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini